lib: [
  "_build/install/default/lib/monkey/META" {"META"}
  "_build/install/default/lib/monkey/opam" {"opam"}
  "_build/install/default/lib/monkey/monkey__Lexer.cmi" {"monkey__Lexer.cmi"}
  "_build/install/default/lib/monkey/monkey__Lexer.cmx" {"monkey__Lexer.cmx"}
  "_build/install/default/lib/monkey/monkey__Lexer.cmt" {"monkey__Lexer.cmt"}
  "_build/install/default/lib/monkey/lexer.ml" {"lexer.ml"}
  "_build/install/default/lib/monkey/monkey.cmi" {"monkey.cmi"}
  "_build/install/default/lib/monkey/monkey.cmx" {"monkey.cmx"}
  "_build/install/default/lib/monkey/monkey.cmt" {"monkey.cmt"}
  "_build/install/default/lib/monkey/monkey.ml" {"monkey.ml"}
  "_build/install/default/lib/monkey/monkey__.cmi" {"monkey__.cmi"}
  "_build/install/default/lib/monkey/monkey__.cmx" {"monkey__.cmx"}
  "_build/install/default/lib/monkey/monkey__.cmt" {"monkey__.cmt"}
  "_build/install/default/lib/monkey/monkey__.ml-gen" {"monkey__.ml-gen"}
  "_build/install/default/lib/monkey/monkey__Token.cmi" {"monkey__Token.cmi"}
  "_build/install/default/lib/monkey/monkey__Token.cmx" {"monkey__Token.cmx"}
  "_build/install/default/lib/monkey/monkey__Token.cmt" {"monkey__Token.cmt"}
  "_build/install/default/lib/monkey/token.ml" {"token.ml"}
  "_build/install/default/lib/monkey/monkey.cma" {"monkey.cma"}
  "_build/install/default/lib/monkey/monkey.cmxa" {"monkey.cmxa"}
  "_build/install/default/lib/monkey/monkey.a" {"monkey.a"}
  "_build/install/default/lib/monkey/monkey.cmxs" {"monkey.cmxs"}
  "_build/install/default/lib/monkey/monkey.dune" {"monkey.dune"}
]
bin: [
  "_build/install/default/bin/monkey" {"monkey"}
]
doc: [
  "_build/install/default/doc/monkey/README.md"
]
